# Generated by Django 3.1.5 on 2021-01-13 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'designations',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='Full Name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.IntegerField(choices=[(0, 'Female'), (1, 'Male')])),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('pan_no', models.CharField(max_length=255, unique=True)),
                ('citizenship_no', models.CharField(max_length=255, unique=True)),
                ('join_date', models.DateField()),
                ('picture', models.ImageField(upload_to='pictures/')),
                ('image', models.ImageField(blank=True, default='placeholder.png', upload_to='categories/')),
                ('pan_no_document', models.ImageField(upload_to='pictures/')),
                ('cititzen_document', models.ImageField(upload_to='pictures/')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')])),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdBy', to=settings.AUTH_USER_MODEL)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.designation')),
                ('updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='updatedBy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
