# Generated by Django 3.1.5 on 2021-01-15 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='designation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='employee',
            table=None,
        ),
    ]
