# Generated by Django 3.1.5 on 2021-01-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='citizenship_document',
            field=models.ImageField(blank=True, null=True, upload_to='images/citizenships/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pan_no_document',
            field=models.ImageField(blank=True, null=True, upload_to='images/pans/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/pictures/'),
        ),
    ]
