# Generated by Django 3.1.5 on 2021-01-22 14:31

from django.db import migrations
import django_enumfield.db.fields
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210119_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=django_enumfield.db.fields.EnumField(blank=True, enum=employee.models.Employee.GENDER, null=True),
        ),
    ]
