# Generated by Django 3.1.5 on 2021-01-26 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210125_1044'),
        ('employee', '0006_auto_20210125_0724'),
    ]

    operations = [
    ]
