# Generated by Django 3.1.5 on 2021-01-26 06:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_merge_20210126_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='citizenship_document',
            field=models.ImageField(blank=True, null=True, upload_to='images/citizenships/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pan_no_document',
            field=models.ImageField(blank=True, null=True, upload_to='images/pans/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Phone number must be entered in the format '+977 9999999999'.", max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format '+977 9999999999'.", regex='^\\+977\\s-?\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/pictures/'),
        ),
    ]
