# Generated by Django 3.1.5 on 2021-01-15 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_type', models.CharField(choices=[('annual_leave', 'Annual Leave'), ('sick_leave', 'Sick Leave'), ('bereavement_leave', 'Bereavement Leave'), ('others', 'Others')], max_length=255)),
                ('leave_details', models.CharField(max_length=255)),
                ('reason_for_leave', models.CharField(max_length=500)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')])),
                ('decline_reasons', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee', to='employee.employee')),
                ('request_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_to', to='leave_request.userchoice')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='verified_by', to='employee.employee')),
            ],
        ),
    ]
