# Generated by Django 3.1.5 on 2021-01-25 10:56

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import leave_request.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210125_1044'),
        ('leave_request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('leave_request.leaverequest',),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='decline_reasons',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_details',
            field=django_enumfield.db.fields.EnumField(default=0, enum=leave_request.models.LeaveRequest.LEAVEDETAILS),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=django_enumfield.db.fields.EnumField(enum=leave_request.models.LeaveRequest.LEAVETYPES),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reason_for_leave',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='request_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_to', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=django_enumfield.db.fields.EnumField(blank=True, enum=leave_request.models.LeaveRequest.STATUSES, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='verified_by', to='employee.employee'),
        ),
        migrations.DeleteModel(
            name='UserChoice',
        ),
    ]
