# Generated by Django 3.1.5 on 2021-02-24 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=7)),
                ('allowance', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=3)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=7)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=7)),
                ('effective_date', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_salary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
