# Generated by Django 3.1.5 on 2021-02-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_auto_20210224_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='allowance',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='salary',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='salary',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='salary',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='salary',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
