# Generated by Django 3.1.5 on 2021-02-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_auto_20210224_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='effective_date',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='tax',
            field=models.DecimalField(decimal_places=2, help_text='Calculate in % .', max_digits=5),
        ),
    ]
