# Generated by Django 3.1.5 on 2021-02-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_auto_20210224_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='effective_date',
            field=models.DateTimeField(),
        ),
    ]
